# Generated by Django 4.2.1 on 2023-05-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0003_remove_user_email_verification_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="alternate_phone",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=20),
        ),
    ]
