# Generated by Django 4.2.1 on 2023-05-06 15:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0004_remove_user_alternate_phone_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
