# Generated by Django 4.1.7 on 2023-05-05 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenities",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now_add=True)),
                ("amenity_name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now_add=True)),
                ("hotel_name", models.CharField(max_length=100)),
                (
                    "hotel_email",
                    models.EmailField(default="your@mail.com", max_length=254),
                ),
                ("hotel_phone", models.CharField(default="9876543210", max_length=15)),
                ("hotel_description", models.TextField()),
                ("total_room", models.IntegerField(default=0)),
                ("total_booked_room", models.IntegerField(default=0)),
                ("total_staffs", models.IntegerField(default=10)),
                ("is_avail", models.BooleanField(default=True)),
                (
                    "continent",
                    models.CharField(
                        choices=[
                            ("AF", "Africa"),
                            ("AN", "Antarctica"),
                            ("AS", "Asia"),
                            ("EU", "Europe"),
                            ("NA", "North America"),
                            ("OC", "Oceania"),
                            ("SA", "South America"),
                        ],
                        max_length=2,
                    ),
                ),
                ("street", models.CharField(max_length=100)),
                ("landmark", models.CharField(default="GMT", max_length=100)),
                ("zip_code", models.CharField(default="000000", max_length=20)),
                (
                    "city",
                    smart_selects.db_fields.ChainedForeignKey(
                        chained_field="region",
                        chained_model_field="region_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cities_light.city",
                    ),
                ),
                (
                    "country",
                    smart_selects.db_fields.ChainedForeignKey(
                        chained_field="continent",
                        chained_model_field="continent",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cities_light.country",
                    ),
                ),
                ("hotel_amenities", models.ManyToManyField(to="home.amenities")),
                (
                    "region",
                    smart_selects.db_fields.ChainedForeignKey(
                        chained_field="country",
                        chained_model_field="country_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cities_light.region",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Room_Type",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Single"),
                            ("DOUBLE", "Double"),
                            ("DELUX", "Delux"),
                            ("SUITE", "Suite"),
                            ("DOORMATORY", "Doormatory"),
                            ("OTHERS", "Others"),
                        ],
                        max_length=10,
                    ),
                ),
                ("room_description", models.TextField()),
                ("room_image", models.ImageField(upload_to="room_type_images")),
                ("max_occupancy", models.IntegerField(default=1)),
                ("facilities", models.ManyToManyField(to="home.amenities")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now_add=True)),
                ("room_number", models.IntegerField(default=1)),
                ("floor", models.CharField(max_length=10)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=999.0, max_digits=10),
                ),
                ("room_count", models.IntegerField(default=10)),
                (
                    "room_image",
                    models.ImageField(default="loading.gif", upload_to="room_image"),
                ),
                ("booked_room", models.IntegerField(default=0)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_hotel_name",
                        to="home.hotel",
                    ),
                ),
                (
                    "rooms_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.room_type"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HotelImages",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now_add=True)),
                ("images", models.ImageField(upload_to="hotels")),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="home.hotel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HotelBooking",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now_add=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "booking_type",
                    models.CharField(
                        choices=[("Pre Paid", "Pre Paid"), ("Post Paid", "Post Paid")],
                        max_length=100,
                    ),
                ),
                ("no_of_room", models.IntegerField(default=1)),
                ("room_number", models.IntegerField(blank=True, null=True)),
                ("no_of_people", models.IntegerField()),
                ("customer_desc", models.CharField(max_length=100)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hotel_booking_detail",
                        to="home.hotel",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booked_room_type",
                        to="home.room_type",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_booking_detail",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
