# Generated by Django 4.1.7 on 2023-03-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220518_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_place',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
