# Generated by Django 4.1.7 on 2023-03-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_hotel_hotel_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
